STORE/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('acercade', views.acercade, name = 'acercade'),
    path('busqueda', views.busqueda, name = 'busqueda'),
    path('carrito', views.carrito, name = 'carrito'),
    path('contacto', views.contacto, name = 'contacto'),
    path('pago', views.pago, name = 'pago'),
    path('producto', views.producto, name = 'producto'),
    path('teclado', views.teclado, name = 'teclado'),
    path('ratones', views.ratones, name = 'ratones'),
    path('digitalizadoras', views.digitalizadoras, name = 'digitalizadoras'),
    
    #path('registro', views.registro, name = 'registro'),
    path('update_item', views.updateItem, name = 'update_item'),
    

    
]

TRABAJOFINAL/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('STORE.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('registrarse/', include('USUARIOS.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

USUARIOS/urls.py
from django.urls import path, include
from . import views

app_name = "USUARIOS"
urlpatterns = [
    path('', views.registrarse, name="registrarse"),
]

STORE/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(max_length=200, null=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=200, null=True)
    description = models.CharField(max_length=500, null=True, blank=True)
    price = models.FloatField( null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    
    def __str__(self):
        return self.name


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.id) 

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total
    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total
        
    
class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total

class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    address = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    country = models.CharField(max_length=200, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

STORE/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http import JsonResponse
import json
#from .forms import *
from .models import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required


# Create your views here.
def index(request):

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        cartItems = order.get_cart_items    
        
    else:
        cartItems = []

    products = Product.objects.filter().order_by('-id')[0:3]
    restoproducts = Product.objects.filter().order_by('-id')[3:]


    context = {'products':products, 'restoproducts':restoproducts, 'cartItems': cartItems}

    return render(request,'store/index.html',context)

def acercade(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        cartItems = order.get_cart_items    
        
    else:
        cartItems = []

    context = {'cartItems': cartItems}
    return render(request,'store/acercade.html',context)

def busqueda(request):
    context = {}
    return render(request,'store/busqueda.html',context)

def carrito(request):
    # chequeo si mi user esta autentificado
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_total':0, 'get_cart_items':0}

    context = {'items':items, 'order':order, 'cartItems':cartItems}

    return render(request,'store/carrito.html',context)

def contacto(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        cartItems = order.get_cart_items    
        
    else:
        cartItems = []
    context = {'cartItems':cartItems}
    return render(request,'store/contacto.html',context)

def login(request):

    context = {}
    return render(request,'store/login.html',context)

def pago(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_total':0, 'get_cart_items':0, 'cartItems':0}

    context = {'items':items, 'order':order, 'cartItems':cartItems}
    return render(request,'store/pago.html',context)

def producto(request):

    product = Product.objects.get(id=productId)
    context = {'productid':productId}
    return render(request,'store/producto.html',context)

def registro(request):
    context = {}
    return render(request,'store/registro.html',context)


def updateItem(request):
    data = json.loads(request.body)
    print(type(data))
    productId = data['productId']
    action = data['action']

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)

    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action =='add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action =='remove':
        orderItem.quantity = (orderItem.quantity - 1)
    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    print('Action:', action)
    print('productID:', productId)
    return JsonResponse('Producto añadido', safe=False)

def teclado(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        cartItems = order.get_cart_items    
        
    else:
        cartItems = []
    products = Product.objects.filter(category_id="2")
    context = {'products':products,'cartItems':cartItems}
    return render(request,'store/teclado.html',context)

def digitalizadoras(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        cartItems = order.get_cart_items    
        
    else:
        cartItems = []
    products = Product.objects.filter(category_id="3")
    context = {'products':products,'cartItems':cartItems}
    return render(request,'store/digitalizadoras.html',context)

def ratones(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        cartItems = order.get_cart_items    
        
    else:
        cartItems = []
    products = Product.objects.filter(category_id="1")
    context = {'products':products,'cartItems':cartItems}
    return render(request,'store/ratones.html',context)


def busqueda(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        cartItems = order.get_cart_items    
    else:
        cartItems = []

    if request.method == "POST":
        searched = request.POST.get('searched')
        products = Product.objects.filter(name__contains=searched)
        context={'searched':searched, 'products':products,'cartItems':cartItems}
        return render(request, 'store/busqueda.html',context)
    else:
        context ={'searched':searched, 'cartItems':cartItems}
        return render(request, 'store/busqueda.html',context)
    
    

STORE/templates/store/XXXlogin.html
{% extends 'store/main.html' %}

{% load static %}

{% block content %}

    <h2>Login</h2>
    
{% endblock %}

STORE/templates/store/acercade.html
{% extends 'store/main.html' %}

{% load static %}

{% block content %}
<div class="bg-light">
    <div class="container py-5">
      <div class="row h-100 align-items-center py-5">
        <div class="col-lg-6">
          <h2 class="display-4">Jaguarete KAA S.A.</h2>
          <p class="lead text-muted mb-0">Nuestra empresa fue creada pensando en usted. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus assumenda quae illo dolorum pariatur reiciendis, sunt tempore temporibus possimus veritatis. Sit tempore eligendi, velit nobis ipsam suscipit nemo dolores harum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel distinctio modi laboriosam voluptate ad ducimus consequatur obcaecati! Voluptatibus, doloremque? Tenetur asperiores eum sapiente unde facere, similique labore! Ratione, fugiat itaque.</p>

        </div>
        <div class="col-lg-6 d-none d-lg-block"><img src="/static/images/computershop.jpg" alt="" class="img-fluid"></div>
      </div>
    </div>
  </div>
  
  <div class="bg-white py-5">
    <div class="container py-5">
      <div class="row align-items-center mb-5">
        <div class="col-lg-6 order-2 order-lg-1"><i class="fa fa-bar-chart fa-2x mb-3 text-primary"></i>
          <h2 class="font-weight-light">Nuestro servicio posventa no lo defraudara</h2>
          <p class="font-italic text-muted mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><a href="#" class="btn btn-light px-5 rounded-pill shadow-sm">Quiero saber mas</a>
        </div>
        <div class="col-lg-6 px-5 mx-auto order-1 order-lg-2"><img src="/static/images/IMG_0601.jpg" alt="" class="img-fluid mb-4 mb-lg-0"></div>
      </div>
      <div class="row align-items-center">
        <div class="col-lg-5 px-5 mx-auto"><img src="/static/images/descarga.jpg" alt="" class="img-fluid mb-4 mb-lg-0"></div>
        <div class="col-lg-6"><i class="fa fa-leaf fa-2x mb-3 text-primary"></i>
          <h2 class="font-weight-light">La mejor oferta de perifericos</h2>
          <p class="font-italic text-muted mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><a href="#" class="btn btn-light px-5 rounded-pill shadow-sm">Quiero saber mas</a>
        </div>
      </div>
    </div>
  </div>
  
  <div class="bg-light py-5">
    <div class="container py-5">
      <div class="row mb-4">
        <div class="col-lg-5">
          <h2 class="display-4 font-weight-light">Nuestro equipo</h2>
          <p class="font-italic text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        </div>
      </div>
  
      <div class="row text-center">
        <!-- Team item-->
        <div class="col-xl-3 col-sm-6 mb-5">
          <div class="bg-white rounded shadow-sm py-5 px-4"><img src="/static/images/cindy500.jpg" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
            <h5 class="mb-0">Manuella Nevoresky</h5><span class="small text-uppercase text-muted">CEO - Fundadora</span>
            <ul class="social mb-0 list-inline mt-3">
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-facebook-f"></i></a></li>
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-twitter"></i></a></li>
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-instagram"></i></a></li>
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>
        <!-- End-->
  
        <!-- Team item-->
        <div class="col-xl-3 col-sm-6 mb-5">
          <div class="bg-white rounded shadow-sm py-5 px-4"><img src="/static/images/andrewLevy500.jpg" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
            <h5 class="mb-0">Samuel Hardy</h5><span class="small text-uppercase text-muted">CEO - Fundador</span>
            <ul class="social mb-0 list-inline mt-3">
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-facebook-f"></i></a></li>
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-twitter"></i></a></li>
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-instagram"></i></a></li>
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>
        <!-- End-->
  
        <!-- Team item-->
        <div class="col-xl-3 col-sm-6 mb-5">
          <div class="bg-white rounded shadow-sm py-5 px-4"><img src="/static/images/mike.jpg" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
            <h5 class="mb-0">Tom Sunderland</h5><span class="small text-uppercase text-muted">Programador - Fundador</span>
            <ul class="social mb-0 list-inline mt-3">
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-facebook-f"></i></a></li>
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-twitter"></i></a></li>
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-instagram"></i></a></li>
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>
        <!-- End-->
  
        <!-- Team item-->
        <div class="col-xl-3 col-sm-6 mb-5">
          <div class="bg-white rounded shadow-sm py-5 px-4"><img src="/static/images/mitch500.jpg" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
            <h5 class="mb-0">John Tarly</h5><span class="small text-uppercase text-muted">Diseñador</span>
            <ul class="social mb-0 list-inline mt-3">
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-facebook-f"></i></a></li>
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-twitter"></i></a></li>
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-instagram"></i></a></li>
              <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>
        <!-- End-->
  
      </div>
    </div>
  </div>
  

{% endblock %}

STORE/templates/store/altaproducto.html
{% extends 'store/main.html' %}

{% load static %}

{% block content %}

    <h2>Alta Producto</h2>
    <form method="post" action="/add">
        {% csrf_token %}
        <input type="text" name="name">
        <input type="text" name="description">
        <input type="text" name="price">
        <input type="text" name="category">
        <input type="text" name="image">
        <button type="submit" >Submit</button>
    </form>
    

    
{% endblock %}

STORE/templates/store/busqueda.html
{% extends 'store/main.html' %}

{% load static %}

{% block content %}
<center>
    <h2>Resultados</h2>
    {% if searched %}
    <hr />
    <div class="container col-lg-12 box-element">
      <ul>
        
  
        {% for product in products%}
          <hr>
          
          <div class="row">
              <div style="flex:1"><img class="row-image" src="{{ product.image.url }}" alt=""></div>
              <div style="flex:3"><a href="#">{{ product.name }}</a></div>
              <div style="flex:1">{{product.price}}</div>
              <div style="flex:1"><button data-product="{{product.id}}" data-action="add" class="btn btn-outline-secondary add-btn update-cart">Al carrito</button>
              </div>
        </div>
      
        {% endfor %}
      </ul>
    </div>
  </div>
    {% else %}
        <h2>No has buscado nada aun</h2>
    {% endif %}
    

</center>    
{% endblock %}

STORE/templates/store/carrito.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}

    <div class="row caja" >
        <div class="col-lg-6 container">
            <div class="box-element">
                <a class="btn btn-outline-dark" href="{% url 'index' %}">&#x2190;Continuar comprando</a>

                <br> <br>
            <table class="table">
                <tr>
                    <th>
                        <h5>Numero de productos: <strong>{{order.get_cart_items}}</strong></h5>
                    </th>
                    <th>
                        <h5>Total: <strong>${{order.get_cart_total|floatformat:2}}</strong></h5>
                    </th>
                    <th>
                        <a style = "float:right; margin:5px" class = "btn btn-success" href="{% url 'pago' %}">Pagar</a>
                    </th>
                </tr>

            </table>
        </div>
        <br>
            <div class="box-element">
                <div class="cart-row">
                    <div style="flex:2 "> </div>
                    <div style="flex:2; text-align:center">&nbsp;&nbsp;<Strong>Producto</Strong></div>
                    <div style="flex:1; text-align:right"><strong>Precio</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
                    <div style="flex:1; text-align:right">&nbsp;&nbsp;<strong>Cantidad</strong></div>
                    <div style="flex:1; text-align:right">&nbsp;&nbsp;<strong>Total</strong></div>

                </div>

                {% for item in items %}
                <div class="cart-row">
                    <div style="flex:2"><img class="row-image" src="{{ item.product.image.url }}" alt=""></div>
                    <div style="flex:2">{{item.product.name}}</div>
                    <div style="flex:1">${{item.product.price|floatformat:2}}</div>
                    <div style="flex-1; text-align:right">
                        <div class="quantity">{{item.quantity}}</div>
                    <div class="quantity">
                        
                        <img data-product="{{item.product.id}}" data-action="add" class="update-cart chg-quantity" src="{% static 'images/up.png' %}" alt="">
                        <img data-product="{{item.product.id}}" data-action="remove"  class="update-cart chg-quantity" src="{% static 'images/down.png' %}" alt="">
                        
                    </div>
                </div>
                    <div style="flex:1; text-align:right">${{item.get_total|floatformat:2}}</div>

                </div>
                {% endfor %}
            </div>

        </div>
    </div>

{% endblock %}

STORE/templates/store/contacto.html
{% extends 'store/main.html' %}

{% load static %}

{% block content %}
<div style="margin-top: 5em;" class="container box-element">
<form class="contact_form" action="" method="post" name="contact_form">
    <ul>
      <li>
        <h2>Contacto</h2>
        <span class="required_notification">* Indica campo requerido</span>
      </li>
      <li>
        <label for="name">Nombre:</label>
        <input type="text" name="name" placeholder="Aca va tu nombre .." required />
        <span class="fa valid-icon"></span>
      </li>
      <li>
        <label for="email">Email:</label>
        <input type="email" name="email" placeholder="john_doe@example.com" required />
        <span class="fa valid-icon"></span>
        <span class="form_hint">Formato: "name@something.com"</span>
      </li>
      <li>
        <label for="website">Website:</label>
        <input type="url" name="website" placeholder="http://johndoe.com/" required pattern="(http|https)://.+" />
        <span class="fa valid-icon"></span>
        <span class="form_hint">Formato: "http://someaddress.com"</span>
      </li>
      <li>
        <label for="message">Mensaje:</label>
        <textarea name="message" cols="40" rows="6" required></textarea>
        <span class="fa valid-icon"></span>
      </li>
      <li>
        <button class="submit" type="submit">Enviar</button>
      </li>
    </ul>
  </form>
  
</div>    
{% endblock %}

STORE/templates/store/main.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
  <head>
    <link rel='shortcut icon' type='image/x-icon' href='/static/images/favicon.ico' />
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
      integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />

    <script type="text/javascript">
      var user = "{{request.user}}";
      function getToken(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== "") {
          const cookies = document.cookie.split(";");
          for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === name + "=") {
              cookieValue = decodeURIComponent(
                cookie.substring(name.length + 1)
              );
              break;
            }
          }
        }
        console.log('cookie:',cookieValue)
        return cookieValue;
      }
      const csrftoken = getToken("csrftoken");
      console.log('cookie:',csrftoken)

    </script>
    <title>Jaguarete KAA SA</title>
  </head>
  <body>

    <div class="d-flex">
      <div class="mr-auto p-2">
        <a href="{% url 'index' %}">
          <img class="logo" src="{% static 'images/logo.png'%}" alt="
          width="50px"></a
        >
      </div>
      <div class="form-inline p-2">

        {% if not user.is_authenticated %}
        <a style="margin:5px;" href="{% url 'login' %}" class="btn btn-primary">Login</a>
        <a style="margin:5px;"href="{% url 'USUARIOS:registrarse' %}" class="btn btn-warning">Registro</a>
        {% endif%}
        {% if user.is_authenticated %}
        <a style="padding:5px;" href="{% url 'logout' %}" class="btn btn-primary">Log out</a>
        {% endif %}
        {% if not request.user.username == "yaskad" %}
        <a href="{% url 'carrito' %}">
          <img id="cart-icon" src="{% static 'images/carrito.png'%}" alt="
          width="50px"></a>
        
        <p id="cart-total">{{cartItems}}</p>
        {% endif %}        
      </div>
    </div>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'index' %}">Tienda</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <!-- <li class="nav-item active">
              <a class="nav-link" href="#">Inicio <span class="sr-only">(current)</span></a>
            </li> -->
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              id="navbarDropdown"
              role="button"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              Categorias
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'ratones' %}">Ratones</a>
              <a class="dropdown-item" href="{% url 'teclado' %}">Teclados</a>
              <a class="dropdown-item" href="{% url 'digitalizadoras' %}">Digitalizadoras</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'acercade' %}">Acerca de</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contacto' %}">Contacto</a>
          </li>
          {% if request.user.username == "yaskad" %}
          <li class="nav-item">
            <a class="nav-link" href="/admin/STORE/product/add/">Nuevo Producto</a>
          </li>
          {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0" method="POST" action="{% url 'busqueda' %}">
          {% csrf_token %}
          <input
            class="form-control mr-sm-2"
            type="search"
            placeholder="Producto a buscar"
            aria-label="Search"
            name = "searched"
          />
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
            Buscar
          </button>
        </form>
      </div>
    </nav>
    {% block content %} {% endblock content %}
    <hr />
    <div class="footer-basic">
      <footer>
        <div class="social">
          <a href="#"><i class="icon ion-social-instagram"></i></a
          ><a href="#"><i class="icon ion-social-snapchat"></i></a
          ><a href="#"><i class="icon ion-social-twitter"></i></a
          ><a href="#"><i class="icon ion-social-facebook"></i></a>
        </div>
        <ul class="list-inline">
          <li class="list-inline-item"><a href="/STORE">Tienda</a></li>
          <li class="list-inline-item"><a href="acercade">Acercade</a></li>
          <li class="list-inline-item"><a href="contacto">Contacto</a></li>
          <li class="list-inline-item"><a href="#">Terminos</a></li>
          <li class="list-inline-item">
            <a href="#">Politica de Privacidad</a>
          </li>
        </ul>
        <a href="{% url 'index' %}">
              <img style="margin:auto;display:block;" class="logo" src="{% static 'images/logo1.jpg'%}" alt=""></a
            >
        
        <p class="copyright">Jaguarete KAA S.A. © 2021</p>
        
      </footer>
    </div>
    <hr />
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
      integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
      crossorigin="anonymous"
    ></script>
    <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
  </body>
</html>